language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
install:
  - npm install electron-prebuilt
  - npm install
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" npm run test
addons:
  apt:
    packages:
      - libgtk2.0-0
      - libgconf-2-4
      - libasound2
      - libxtst6
      - libxss1
      - libnss3
      - xvfb
      - x11-xkb-utils
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-scalable
      - xfonts-cyrillic
      - x11-apps
      - clang
      - libdbus-1-dev
      - libnotify-dev
      - libgnome-keyring-dev
      - libgconf2-dev
      - libcap-dev
      - libcups2-dev
      - libxtst-dev
      - gcc-multilib
      - g++-multilib
